name: build-checks-4

on: 
  workflow_dispatch:
  push:

jobs:
  tests:
    name: Format and tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Test
        run: echo "Test step"
