name: deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: [workflow]
    branches: ['workflow-test']
    types:
      - completed

jobs:
  hello-world:
    name: Hello world1
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Check-out devops repository
      uses: actions/checkout@v1
  
    - name : call temp.yaml
      uses: ./.github/actions/temp-action
    
    - name: Run script
      run: python lambda_function.py > output.txt
      shell: sh
      
    - name : Display output
      run : cat output.txt 
