name: deploy

on:
  workflow_run:
    workflows: [workflow]
    types:
      - completed
  workflow_dispatch:

jobs:
  hello-world:
    name: Hello world12
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
    - name: Check-out devops repository
      uses: actions/checkout@v1
  
    - name : call temp.yaml
      uses: ./.github/actions/temp-action
    
    - name: Run script
      run: python lambda_function.py > output.txt
      shell: sh
      
    - name : Display output
      run : cat output.txt 
