name: upload-tests

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ build-checks-3 ]
    branches: [ test-4 ]
    types:
      - completed

jobs:
  run-tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Upload tests
    runs-on: ubuntu-latest
    steps:
      - name: Run upload-tests
        run: echo "Run upload-tests"
