name: Workflow test

on: push

jobs:
  hello-world:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
    - name: Check-out devops repository
      uses: actions/checkout@v2

    - name: Run script
      run: python lambda_function.py > output.txt
      shell: sh
      
    - name : Display output
      run : cat output.txt
  
  temp-job:
    runs-on: ubuntu-latest
    needs : [hello-world]
    steps:
      - name: Check-out temp-job repo
        uses: actions/checkout@v2
      - name : call temp.yaml
        uses: ./.github/actions/temp-action/temp.yaml
