name: workflow

on: 
  workflow_run:
    workflows: [deply]
    branches:
      - '**'
      # - '!main'
    types:
      - completed

jobs:
  workflow-job:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Print workflow_run information
        run: echo "$GITHUB_CONTEXT"

      - name: Check for PR to Main for the current branch for this branch
        run: |
          # BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          BRANCH_NAME=${{github.event.workflow_run.head_branch}}
          
          echo "$BRANCH_NAME"
          PR_COUNT=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                     -H "Accept: application/vnd.github.v3+json" \
                     "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&base=main" | \
                     jq --arg BRANCH_NAME "$BRANCH_NAME" \
                     '[.[] | select(.head.ref == $BRANCH_NAME)] | length' )
          if [ "$PR_COUNT" -gt 0 ]; then
            echo "Branch has open pull request to main."
            echo PR_EXISTS=true>>$GITHUB_ENV
          else
            echo "Branch does not have open pull request to main."
            echo PR_EXISTS=false>>$GITHUB_ENV
          fi
      - name: Print workflow_run information
        if: env.PR_EXISTS == true && env.PR_EXISTS == true
        run: echo "PR Exists"
