name: workflow

on: push

jobs:
  job-1:
    name: Hello world
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - name: Check-out devops repository
      uses: actions/checkout@v1
  
    - name : call temp.yaml
      uses: ./.github/actions/temp-action
    
    - name: Run script
      run: python lambda_function.py > output.txt
      shell: sh
      
    - name : Display output
      run : cat output.txt 
  
  job-2:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps: 
    - name: Check-out devops repository
      uses: actions/checkout@v1
  
    - name : call temp.yaml
      uses: ./.github/actions/temp-action
      with:
        environment: abcd
